modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
issueTrackerURL="https://github.com/sux2mfgj/clayore/issues"
license="The MIT License (MIT)"
displayURL="https://github.com/sux2mfgj/clayore"
logoFile="logo.png" #optional
authors="sux2mfgj" #optional

[[mods]] #mandatory
    modId="clayore" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="ClayOre" #mandatory
    description='''
This mod provides Clay ores in the world.
    '''


[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"

